services:

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes: 
      - data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "YourPW"
    ports:
      - "5432:5432"
  
  cache:
    image: redis:7-alpine
    restart: always
    volumes:
      - cache:/data
    ports: 
      - "6379:6379"
    command: redis-server --save 10 1 --loglevel warning --requirepass YourPW

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=YourPW
      - REDIS_HOST=cache
      - REDIS_PASSWORD=YourPW
      - SECRET_KEY=sechrefd
    depends_on:
      - db
      - cache


volumes:
  data:
  cache:
    driver: local